name: Build Linux Prebuilt

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: 'Install Build Deps'
        run: |
          sudo apt-get install -y build-essential make cmake git pkg-config liblzo2-dev libjpeg-turbo8-dev libpng-dev zlib1g-dev nasm libvncserver-dev

      - name: 'Build N1-VNC'
        run: |
          mkdir prebuilt
          go env
          go build -o prebuilt/n1-vnc .

      - name: 'Create INSTALL'
        run: |
          echo "Before using, please make sure libvncserver.so.1 exists in the system." > prebuilt/INSTALL
          echo "" >> prebuilt/INSTALL
          echo "You can use the following command to install it in Ubuntu/Debian (lower versions of the system need to compile manually):" >> prebuilt/INSTALL
          echo "apt-get install -y libvncserver1" >> prebuilt/INSTALL
          echo "" >> prebuilt/INSTALL
          echo "Have fun!" >> prebuilt/INSTALL
      
      - name: 'Pack N1-VNC'
        run: |
          zip -r n1-vnc_prebuilt_linux.zip prebuilt/*

      - name: 'Upload artifact'
        uses: actions/upload-artifact@v2
        with:
           name: n1-vnc_prebuilt_linux
           path: n1-vnc_prebuilt_linux.zip
