name: Build Windows Redist

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: 'Setup MSYS2'
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          cache: false
          install: >-
            git
            zip
            make
            mingw-w64-x86_64-go
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-ninja
            mingw-w64-x86_64-gcc-libs
            mingw-w64-x86_64-libjpeg-turbo
            mingw-w64-x86_64-libpng
            mingw-w64-x86_64-lzo2
            mingw-w64-x86_64-zlib

      - name: 'Download libvncserver'
        run: |
          mkdir external
          cd external
          git clone https://github.com/LibVNC/libvncserver.git -b LibVNCServer-0.9.14

      - name: 'Build libvncserver'
        run: |
          cd external/libvncserver
          mkdir build
          cd build
          cmake -DBUILD_SHARED_LIBS=ON -DWITH_EXAMPLES=OFF -DWITH_OPENSSL=OFF  -DWITH_GNUTLS=OFF -DWITH_GCRYPT=OFF -DCMAKE_INSTALL_PREFIX=/mingw64/ ..
          cmake --build .
          cmake --install .

      - name: 'Build N1-VNC'
        run: |
          mkdir redist
          go env
          go build -o redist/n1-vnc.exe .

      - name: 'Copy Windows Redist Deps'
        run: |
          cp /mingw64/bin/libgcc_s_seh-1.dll redist/
          cp /mingw64/bin/libvncserver.dll redist/
          cp /mingw64/bin/libwinpthread-1.dll redist/
          cp /mingw64/bin/libjpeg-8.dll redist/
          cp /mingw64/bin/liblzo2-2.dll redist/
          cp /mingw64/bin/libpng16-16.dll redist/
          cp /mingw64/bin/zlib1.dll redist/
      
      - name: 'Pack Windows Redist'
        run: |
          cd redist
          zip -r ../n1-vnc_redist_win.zip *

      - name: 'Upload artifact'
        uses: actions/upload-artifact@v2
        with:
           name: n1-vnc_redist_win
           path: n1-vnc_redist_win.zip
